# Generated by Django 3.1.7 on 2021-04-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Tag',
            field=models.CharField(choices=[('choice1', 'Books'), ('choice2', 'Instruments'), ('choice3', 'Bikes'), ('choice4', 'Clothes')], default='choice1', max_length=100),
            preserve_default=False,
        ),
    ]
