# Generated by Django 3.1.6 on 2021-04-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_item_availabe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Availabe',
            new_name='Available',
        ),
    ]
